### ISSUE TITLE
Art

### ISSUE THREAD

**Issue by andall1811** [OldSchoolCoder1/TrashThrasher#23]
- Trash Objects need art/collision adjustments.  One trash type for now, others when prototype is functional.
- Planet
- Background
- Different saucer?
- Character animation
- Explosion animation
- Pickle Boss (not animated)

**Comment by that-guy-matt** [comment]
- [x]     Trash Objects need art/collision adjustments. One trash type for now, others when prototype is functional (used a trash bag with a rectangle collision box, might be best for objects to stack properly and allow character to stand on?)
- [x]     Planet (created scene with one planet, added collision)
- [x]     Background (added to your level scene... looks good)
- [ ]     Different saucer? (no?)
- [x]     Character animation
- [x]     Explosion animation (found good resource but I animated it poorly.. a bit crooked, but looks fine for now)
- [x]     Pickle Boss (not animated) (yup)

**Comment by that-guy-matt** [comment]
Pushed changes to dev branch.
