### ISSUE TITLE
Projectile object

### ISSUE THREAD

**Issue by andall1811** [OldSchoolCoder1/TrashThrasher#5]
Projectile .tscn with Sprite2D placeholder texture, Area2D, and CollisionObject2D.

Should move up at a rate determined by designer.

**Comment by andall1811** [comment]
Matt started the scene/code for this, but it is not spawning or working.  Please troubleshoot. :)

**Comment by that-guy-matt** [comment]
I added a reload timer to projectile spawner so player may not fire faster than every 1 second.
I pushed changes to development branch.
